# Generated by Django 3.0.8 on 2020-08-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20200720_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPA'), ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARA'), ('DF', 'DISTRITO FEDERAL'), ('ES', 'ESPIRITO SANTO'), ('GO', 'GOIAS'), ('MA', 'MARANHAO'), ('MT', 'MATO GROSSO'), ('MS', 'MATO GROSSO DO SUL'), ('MG', 'MINAS GERAIS'), ('PA', 'PARA'), ('PB', 'PARAIBA'), ('PR', 'PARANÁ'), ('PE', 'PERNAMBUCO'), ('PI', 'PIAUI'), ('RJ', 'RIO DE JANEIRO'), ('RN', 'R G NORTE'), ('RS', 'R G SUL'), ('RO', 'RONDONIA'), ('RR', 'RORAIMS'), ('SC', 'SANTA CATARINA'), ('SP', 'SAO PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')], max_length=2, null=True),
        ),
    ]
