# Generated by Django 3.0.8 on 2020-08-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20200830_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervalo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=40)),
                ('pagini', models.DateField(blank=True, null=True)),
                ('pagfim', models.DateField(blank=True, null=True)),
                ('lctini', models.DateField(blank=True, null=True)),
                ('lctfim', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Intervalo',
                'managed': False,
            },
        ),
    ]
