# Generated by Django 3.0.8 on 2020-09-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_intervalo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='intervalo',
            table='intervalo',
        ),
    ]
