# Generated by Django 3.0.8 on 2020-09-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20200831_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'managed': False, 'ordering': ['municipio']},
        ),
        migrations.AlterModelOptions(
            name='contas',
            options={'managed': False, 'ordering': ['conta']},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': True, 'ordering': ['nome']},
        ),
    ]
