# Generated by Django 2.2.14 on 2020-07-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': True},
        ),
    ]
