# Generated by Django 2.2.14 on 2020-07-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20200715_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='centro',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
