# Generated by Django 2.2.14 on 2020-07-15 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_fornecedor_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='centro',
            field=models.ForeignKey(blank=True, db_column='centro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Centro'),
        ),
    ]
