# Generated by Django 3.0.8 on 2020-07-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20200718_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='centro',
        ),
    ]
